import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

// font-family "Geist" initialized
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

// font-family "Geist Mono" initialized
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// Metadata for the root layout
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

/**
 * Root layout component for the application.
 * 
 * @returns {JSX.Element} The root layout component.
 */
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Toaster />
				{children}
			</body>
		</html>
	);
}
